# BASIC AUTH
proxy:
  ### PERSONALIZATION ###
  title: ShinyStudio
  hide-navbar: false
  logo-url: file:///opt/shinyproxy/templates/grid-layout/assets/img/logo.png
  favicon-path: /opt/shinyproxy/templates/grid-layout/assets/img/logo.png
  template-path: ./templates/grid-layout
  ### AUTHENTICATION ###
  admin-groups: ['admins']
  authentication: simple
  users:
  - name: ${USER}
    password: ${PASSWORD}
    groups: admins
  ### DANGER ZONE ###
  port: 8080 # don't change!
  landing-page: /
  container-wait-time: 30000
  heartbeat-rate: 15000
  heartbeat-timeout: 120000
  docker:
    internal-networking: true
  specs:
    - id: reports
      display-name: Apps & Reports
      logo-url: 'fas fa-chart-line'
      container-image: dm3ll3n/shinystudio:${TAG}
      container-cmd: [ "shiny-server" ]
      container-network: shinystudio-net
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}/_apps:/srv/shiny-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: documents
      display-name: Documents
      logo-url: 'fas fa-file-alt'
      container-image: dm3ll3n/shinystudio:${TAG}
      container-cmd: [ "shiny-server" ]
      container-network: shinystudio-net
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}/_docs:/srv/shiny-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: personal
      display-name: Personal
      logo-url: 'far fa-folder-open'
      container-image: dm3ll3n/shinystudio:${TAG}
      container-cmd: [ "shiny-server" ]
      container-network: shinystudio-net
      container-volumes:
        - "${CONTENT_PATH}/users/#{proxy.userId}:/srv/shiny-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: rstudio
      display-name: RStudio
      logo-url: 'fab fa-r-project'
      container-image: dm3ll3n/shinystudio:${TAG}
      container-cmd: [ "rstudio" ]
      container-network: shinystudio-net
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}/.rstudio:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      description: Full Screen
      port: 8787
      access-groups: [ 'admins' ]
    - id: vscode
      display-name: Visual Studio Code
      logo-url: 'fas fa-terminal'
      container-image: dm3ll3n/shinystudio:${TAG}
      container-cmd: [ "vscode" ]
      container-network: shinystudio-net
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}/.vscode:/home/#{proxy.userId}/.local/share/code-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      description: Full Screen
      port: 8080
      access-groups: [ 'admins' ]
